xwayland {
    force_zero_scaling = true
}

## MISC
misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
}

## INPUTS

# use natural scrolling
input {
  # Capslock as escape key
  kb_options = caps:escape
  # Natural scrolling for all input devices
  natural_scroll = true

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true
  }
}

decoration {
    # Use round window corners
    rounding = 8
}

# Override opening terminal with Ghostty. By default Alacritty is used for Omarchy, but when I override it with Ghostty
# including custom font-size, floating windows (e.g. cpu) will not be shown.
unbind = SUPER, RETURN
bindd = SUPER, RETURN, Terminal, exec, ghostty --working-directory="$(omarchy-cmd-terminal-cwd)"

unbind = SUPER SHIFT, T
bindd = SUPER SHIFT, T, Todoist, exec, omarchy-launch-webapp "https://app.todoist.com/app/today"

# NOTE(robin): allow alt-tab within Citrix clients
bind = ALT, TAB, pass, class:^(Wfica)$

bindd = SUPER CTRL, Q, Lock Screen, exec, omarchy-system-lock

# Allow toggling of internal monitor
bindd = SUPER ALT, 0, Toggle internal monitor, exec, omarchy-hyprland-monitor-internal-toggle

## WINDOW RULES
windowrule = size 1024 768, match:tag floating-window

# NOTE(robin): to disable transparancy for all windows
windowrule = match:class .*, opacity 1 override
# Launch Chromium into workspace 2
windowrule = match:class chromium, workspace 2
# Launch Helium into workspace 2
windowrule = match:class helium, workspace 2
# Launch ICAClients into workspace 3 silently
windowrule = match:class Wfica, workspace 3 silent
# Prevent fullscreen for icaclient
windowrule = match:class Wfica, suppress_event fullscreen

# vim: ft=hyprlang
