#!/usr/bin/env bash

VERSION="release-0.12"
INSTALLER_DIR="~/code/playground/neovim"

if [ $(uname) == "Linux" ]; then
    echo "Installing Neovim version $VERSION..."

    if [ ! -d $INSTALLER_DIR ]; then
        mkdir -p $(basename $INSTALLER_DIR)
        git clone https://github.com/neovim/neovim.git $INSTALLER_DIR
    fi

    git -C $INSTALLER_DIR fetch --all
    git -C $INSTALLER_DIR checkout $VERSION

    make -C $INSTALLER_DIR clean
    make -C $INSTALLER_DIR CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=/usr/local
    sudo make -C $INSTALLER_DIR install
fi

echo "Downloading my Neovim config..."
[[ ! -d $HOME/.config/nvim ]] && git clone https://github.com/rgruyters/nvim.git $HOME/.config/nvim

# vi: ft=bash
